### ISSUE TITLE
File name customization unclear / not working

### ISSUE THREAD

**Issue by lackovic** [EslaMx7/PasteIntoFile#17]
It is unclear from the README "_to change default filename format ("dd-MM-yyyy HH-mm-ss") use for example: `/filename yyyy-MM-dd_HHmm`_" where/how the command can be issued.

I tried running `PasteIntoFile.exe /filename yyyy-MM-dd_HHmm` [from the command line](https://github.com/EslaMx7/PasteIntoFile/blob/83527b9208a4d8c9218fa886e35cc9ecf5ddb020/PasteIntoFile/Program.cs#L33) but that did not have any effect.

I tried to change the date format by setting the [system register key](https://github.com/EslaMx7/PasteIntoFile/blob/83527b9208a4d8c9218fa886e35cc9ecf5ddb020/PasteIntoFile/frmMain.cs#L33) to `yyyy-MM-dd HH-mm-ss` but that did not work.

Using pasteintofile `v1.4.0` installed via [Chocolatey](https://chocolatey.org/packages/pasteintofile).

**Comment by EslaMx7** [comment]
@lackovic Sorry for the inconvenience about this feature, because it was merged to the master without being released as a new version. I will release this version today so you can download the new executable.

**Comment by lackovic** [comment]
> @lackovic Sorry for the inconvenience about this feature

No problem at all! Thank you for creating this application, great work and very useful!

A couple of suggestions, if I may...

1. I would use the international format [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) as default file name format, that would allow to have the files sorted by name to be sorted by date as well;

1. Specify in the README the `/filename yyyy-MM-dd_HHmm` option to change the default file name format has to be passed as argument to the executable from a terminal.

I am happy to open a PR if you agree.

**Comment by EslaMx7** [comment]
@lackovic Sure, I will be happy to merge it if you have time to make it, as I was so busy yesterday.

**Comment by lackovic** [comment]
> @lackovic Sure, I will be happy to merge it if you have time to make it, as I was so busy yesterday.

Here you are:

- https://github.com/EslaMx7/PasteIntoFile/pull/18

- https://github.com/EslaMx7/PasteIntoFile/pull/19

**Comment by EslaMx7** [comment]
Thank you very much for your contributions, really appreciated.
Merged #18 and #19

**Comment by lackovic** [comment]
You are welcome! Happy to help :-)

Looking forward to the new version release!
