### ISSUE TITLE
Please detail the method of adding and removing Paste into file from right click menu

### ISSUE THREAD

**Issue by HAOOFE** [EslaMx7/PasteIntoFile#21]
Thanks for the hard works firstly..
For some reason I want to removed paste into file from my right click menu.. but i just can under stand this.
----
To remove the Paste Into File entry from the File Explorer context menu:
PasteIntoFile /unreg
----

My PasteIntoFile.exe is located at D:\Will\pasteIntoFile.exe.. can you please let me know the full command message that i should put into the Powershell to run?.

**Comment by rdllngr** [comment]
To remove PasteIntoFile from the context menu (right click menu):

1. Open the Command Prompt as an administrator – search for "cmd" in the Start Menu.
2. Type the directory name + PasteIntoFile.exe + /unreg.

For example:
C:\Users\MyName\Desktop\PasteIntoFile.exe /unreg

3. Then Enter. A message box will appear confirming the action.

**Comment by HAOOFE** [comment]
Got it. Cheers.
