### ISSUE TITLE
great tool sir

### ISSUE THREAD

**Issue by zffffff** [EslaMx7/PasteIntoFile#3]
very useful

**Comment by bsjut** [comment]
super useful tool for me. I used the commercial PasteAsAFile application by vdsfreak previously and this had way more load (more than 12 MB) and cost 10 USD. your version is super efficient, fast, works nicely. I'm happy to donate for a few coffees / bagels if you put up a PayPal address or other means of supporting you, i.e. patreon

**Comment by EslaMx7** [comment]
@bsjut Thank you very much for your supported comment, That just made my day.
I'm so glad that my work helped you get your work done easily and I'm really proud of your appreciated feedback, this encouraged me to publish more useful tools like the one you used.
Regarding the donation suggestions -which is very nice from you- I just made Patreon page now: 
https://www.patreon.com/eslamx7 

Thank you, Bjoern

Regards,
Eslam

**Comment by bsjut** [comment]
Hi Eslam, 

I just pledged 10 USD via Patreon. Not sure though if you need to add something to Patreon first, to receive it, as you've set a "per app" payment goal. Enjoy!
