### ISSUE TITLE
Copyright infringement 

### ISSUE THREAD

**Issue by chris-insuresign** [EslaMx7/PasteIntoFile#4]
I am the developer of the real Paste As File (http://paf.vdsfreak.com) Please change the name of your product to prevent further action.

**Comment by EslaMx7** [comment]
@chris-insuresign : First of all, I'm so sorry if this repository caused you any problems, it was `UNINTENDED` to name it as your original product, i don't even know if it exists as commercial, the idea just came to my mind a long ago then decided to publish it to my account 2 years ago.
However, i renamed the repository name to be ***Paste Into Files*** to reduce the confusion to your users and the search engines too.

Regards,
Eslam

**Comment by sibojan** [comment]
Hi EslaMx7,

I liked your software and it worked very well. Plus, it is free of charge. I like it.

**Comment by jcamp** [comment]
Hi Eslam

Regarding the name changing (as per Chris's comment above). When you install your software it is registering a context menu addition of 'paste as file' and not 'paste into file' - **which is conflicting with the "Paste As File" application**. Please rename your 'paste as file' context menu to 'paste into file' in order to co-exist.

**Comment by jcamp** [comment]
> Hi Eslam
> 
> Regarding the name changing (as per Chris's comment above). When you install your software it is registering a context menu addition of 'paste as file' and not 'paste into file' - **which is conflicting with the "Paste As File" application**. Please rename your 'paste as file' context menu to 'paste into file' in order to co-exist.

Can you update your registry entry please as requested...

**Comment by EslaMx7** [comment]
@jcamp done and released: https://github.com/EslaMx7/PasteIntoFile/releases/tag/v1.3
