### ISSUE TITLE
Small feature request: initial focus + enter to save

### ISSUE THREAD

**Issue by dsanalytics** [EslaMx7/PasteIntoFile#9]
Thanks for this great utility!

Currently, one has to tab to get to the file name text box and then tab to get to save button. 

So, would it be possible to have:
1) Focus in the file name text box when dialog opens with date/time text selected + 
2) Pressing Enter key there to act as Save?

Thanks for your time.

![image](https://user-images.githubusercontent.com/32625394/44067606-f4848d52-9f3b-11e8-8c70-bfae0a760605.png)

**Comment by FlandiaYingman** [comment]
+1

**Comment by EslaMx7** [comment]
@dsanalytics @FlandiaYingman done and released: https://github.com/EslaMx7/PasteIntoFile/releases/tag/v1.4

**Comment by dsanalytics** [comment]
Thx! P.S. Not a big deal and it's working great, but next time please keep exe name and RightClick menu name the same if possible.
